language: julia
notifications:
  email: false
matrix:
  include:
    - os: linux
      julia: release
      env: TESTCMD="xvfb-run julia"
    - os: linux
      julia: nightly
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: release
      env: TESTCMD="julia"
    - os: osx
      julia: nightly
      env: TESTCMD="julia"
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); Pkg.build("Blink"); Pkg.test("Blink"; coverage=true)'
